# This is a basic workflow to help get started with Actions

name: Sync to Hugging Face hub

# controls when the workflow will be run
on:
  push: 
    branches: [ main ]
  
  # Allows you to run this workflow manually from Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 
    - name: Add remote
      env: 
        HF: ${{ secrets.HF }}
      run: git remote add space https://pg2286:$HF@huggingface.co/spaces/pg2286/image-classification
    - name: Push to hub
      env: 
        HF: ${{ secrets.HF }}
      run: git push --force https://pg2286:$HF@huggingface.co/spaces/pg2286/image-classification main
